test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,6 @@
 version: 2.1
 
 commands:
-
   install_awscli:
     description: Install AWS CLI v2
     steps:
@@ -71,7 +70,7 @@ commands:
               npm install
               npm run migration:revert
             fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -90,7 +89,6 @@ jobs:
           paths: [frontend/node_modules]
           key: frontend-deps
 
-
   build-backend:
     docker:
       - image: cimg/node:13.8.0
@@ -101,13 +99,12 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             cd backend
-             npm install
-             npm run build
+            cd backend
+            npm install
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-deps
-
 
   test-frontend:
     docker:
@@ -122,7 +119,6 @@ jobs:
             cd frontend
             npm install
             npm test
-                
 
   test-backend:
     docker:
@@ -153,7 +149,6 @@ jobs:
             npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
 
-
   scan-backend:
     docker:
       - image: cimg/node:13.8.0
@@ -169,7 +164,6 @@ jobs:
             npm audit fix --force --audit-level=critical
             npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
-
 
   deploy-infrastructure:
     docker:
@@ -210,9 +204,7 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
 
-      
       - destroy-environment
-
 
   configure-infrastructure:
     docker:
@@ -239,21 +231,12 @@ jobs:
     steps:
       - checkout
       - install_awscli
-
       - run:
           name: Run migrations
           command: |
-            echo printenv
-            printenv >> ./backend/.env
             cd backend
-            npm i
-            npm audit fix --force --audit-level=critical
-            npm audit fix --force --audit-level=critical
-            npm audit --audit-level=critical
-            npm audit fix --audit-level=critical 
-            npm run migrations >> migrations_dump.txt
-            cat migrations_dump.txt
-            pwd
+            npm install
+            npm run migrations > migrations_dump.txt
       - run:
           name: Send migration status to kvdb.io
           command: |
@@ -263,7 +246,6 @@ jobs:
             fi
       - destroy-environment
       - revert-migrations
-     
 
 #  deploy-frontend:
 #    docker:
@@ -298,7 +280,7 @@ jobs:
 #
 #      - destroy-environment
 #      - revert-migrations
-#                    
+#
 #  deploy-backend:
 #    docker:
 #      - image: cimg/base:stable
@@ -343,61 +325,88 @@ jobs:
 #
 #  smoke-test:
 #    docker:
-#      # Lightweight Docker image 
+#      - image: cimg/base:stable
 #    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Install dependencies
-#          command: |
-#            # your code here
-#      - run:
-#          name: Get backend url
-#          command: |
-#            # your code here
+#      - checkout
+#      - install_awscli
+#      - install_nodejs
 #      - run:
 #          name: Backend smoke test.
 #          command: |
-#            # your code here
+#            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#              --output text)
+#
+#            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+#            if curl -s $API_URL/api/status | grep "ok"
+#            then
+#              exit 0
+#            else
+#              exit 1
+#            fi
 #      - run:
 #          name: Frontend smoke test.
 #          command: |
-#            # your code here
-#      # Here's where you will add some code to rollback on failure  
+#            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+#            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#            then
+#              exit 0
+#            else
+#              exit 1
+#            fi
+#      - destroy-environment
+#      - revert-migrations
 #
 #  cloudfront-update:
 #    docker:
-#      # Docker image here that supports AWS CLI
+#      - image: cimg/base:stable
 #    steps:
-#      # Checkout code from git
+#      - checkout
+#      - install_awscli
+#      - install_nodejs
 #      - run:
-#          name: Install dependencies
+#          name: Save Old Workflow ID to kvdb.io
 #          command: |
-#            # your code here
+#            export OLD_WORKFLOW_ID=$(aws cloudformation \
+#                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+#                      --no-paginate --output text)
+#            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+#            curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
 #      - run:
 #          name: Update cloudfront distribution
 #          command: |
-#            # your code here
-#      # Here's where you will add some code to rollback on failure  
+#            aws cloudformation deploy \
+#              --template-file .circleci/files/cloudfront.yml \
+#              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#              --stack-name InitialStack
+#      - destroy-environment
+#      - revert-migrations
 #
-#cleanup:
+#  cleanup:
 #    docker:
-#      # Docker image here
+#      - image: cimg/base:stable
 #    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Get old stack workflow id
-#          command: |
-#            # your code here
-#            export OldWorkflowID="the id here"
-#            export STACKS=[] #put the list of stacks here
+#      - checkout
+#      - install_awscli
+#      - install_nodejs
 #      - run:
 #          name: Remove old stacks and files
 #          command: |
+#            export STACKS=($(aws cloudformation list-stacks \
+#                --query "StackSummaries[*].StackName" \
+#                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+#            echo Stack names: "${STACKS[@]}"
+#
+#            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+#            echo Old Workflow ID: $OldWorkflowID 
+#
 #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
 #            then
-#              # your code here
+#              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+#              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
 #            fi
-            
 
 workflows:
   default:
